export { queryMemories, queryMemoriesVector, backfillEmbeddings, addMemory, removeMemory, decayMemories, dynamicDecayMemories, computeMemoryValue, promoteMemories, formatMemoriesForContext, addReminder, getDueReminders, fireReminder, getUnconsolidatedEpisodic, markConsolidated, decayMemoryAssociations, initMemoryAssociations, getAssociatedMemories, borrowAgentMemories, autoMarkCrossAgentShare, getHibernatedMemories, countHibernatedMemories, getMemoryScore, MEMORY_DECAY_RATE, MEMORY_BLUR_THRESHOLD, MEMORY_HIBERNATE_THRESHOLD, MEMORY_RETRIEVAL_BOOST } from './store';
export type { Reminder } from './store';
export { extractMemories } from './extractor';
export type { ExtractedMemory, MemoryTier, MemoryPerspective } from './types';
export type { ExtractedReminder } from './extractor';
export { analyzeBehavioralPatterns, runBehavioralAnalysis } from './behavioral';
export type { BehavioralPattern } from './behavioral';
export { initMemorySync, registerUserSocket, unregisterUserSocket, broadcastMemoryChange, broadcastDeviceChange, broadcastPreferenceChange } from './sync';
export { buildNarrativeChain } from './narrative';
export type { NarrativeChainResult } from './narrative';
export { evaluateMemoryFirewall, getMemoryFirewallPolicy } from './firewall';
export { dualRetrieve, retrieveRelevantMemories } from './retriever';
export type { RankedMemory, InteractionMemory } from './retriever';
export { getTimeline } from './timeline';
export type { TimelineEntry, TimelineOptions } from './timeline';
export { storeMemory, getMemories, extractKeyFacts, applyPreferenceFacts, formatPreferenceTagsForPrompt, getSensitiveTopicGuard, SENSITIVE_TOPICS } from './crossSession';
export type { CrossSessionMemory, ExtractedFact } from './crossSession';
export { extractKnowledge, storeKnowledge, getKnowledge, formatKnowledgeForContext } from './knowledgeBase';
export type { KnowledgeEntry, ExtractedKnowledge } from './knowledgeBase';
export type { MemoryFirewallDecision, MemoryFirewallPolicy } from './firewall';
export { runDreamCycle, getSleepCycleState } from './dream';
export type { DreamCycleReport, DreamCycleOptions, SleepCycleState } from './dream';
