import { NlpManager } from 'node-nlp';
import path from 'path';

const manager = new NlpManager({ languages: ['zh'] });

manager.addDocument('zh', '你觉得我该不该告诉他', 'ask_opinion');
manager.addDocument('zh', '你认为我应该答应他吗', 'ask_opinion');
manager.addDocument('zh', '我该不该换城市', 'ask_opinion');
manager.addDocument('zh', '你觉得呢', 'ask_opinion');
manager.addDocument('zh', '你怎么看这件事', 'ask_opinion');
manager.addDocument('zh', '你什么观点', 'ask_opinion');
manager.addDocument('zh', '你感觉如何', 'ask_opinion');
manager.addDocument('zh', '你怎么想的', 'ask_opinion');
manager.addDocument('zh', '你的看法是什么', 'ask_opinion');
manager.addDocument('zh', '对此你有什么见解', 'ask_opinion');
manager.addDocument('zh', '你支持哪个', 'ask_opinion');
manager.addDocument('zh', '你的态度是什么', 'ask_opinion');
manager.addDocument('zh', '你怎么评价这个', 'ask_opinion');
manager.addDocument('zh', '你觉得我应该怎么做', 'seek_advice');
manager.addDocument('zh', '你觉得我该怎么做', 'seek_advice');
manager.addDocument('zh', '你觉得我应该怎么办', 'seek_advice');
manager.addDocument('zh', '我应该怎么做会更好', 'seek_advice');
manager.addDocument('zh', '我该怎么做比较合适', 'seek_advice');
manager.addDocument('zh', '帮我看一下我该怎么做', 'seek_advice');
manager.addDocument('zh', '你觉得我该怎么判断', 'seek_advice');
manager.addDocument('zh', '你觉得我应该怎么决定', 'seek_advice');
manager.addDocument('zh', '我现在该怎么做', 'seek_advice');
manager.addDocument('zh', '你觉得我现在应该怎么做', 'seek_advice');
manager.addDocument('zh', '我该怎么办', 'seek_advice');
manager.addDocument('zh', '我应该怎么做', 'seek_advice');
manager.addDocument('zh', '你给个建议', 'seek_advice');
manager.addDocument('zh', '给点建议吧', 'seek_advice');
manager.addDocument('zh', '帮我出出主意', 'seek_advice');
manager.addDocument('zh', '我想听听你的建议', 'seek_advice');
manager.addDocument('zh', '你觉得我该选哪个', 'seek_advice');
manager.addDocument('zh', '你说我该不该去', 'seek_advice');
manager.addDocument('zh', '你有什么好建议', 'seek_advice');
manager.addDocument('zh', '帮我拿个主意', 'seek_advice');
manager.addDocument('zh', '我现在很纠结，给点建议', 'seek_advice');
manager.addDocument('zh', '这种情况我该怎么做', 'seek_advice');
manager.addDocument('zh', '你能帮我分析一下吗', 'seek_advice');
manager.addDocument('zh', '给我一些建议', 'seek_advice');
manager.addDocument('zh', '我应该怎么选', 'seek_advice');
manager.addDocument('zh', '你帮我参谋一下', 'seek_advice');
manager.addDocument('zh', '我该走哪条路', 'seek_advice');
manager.addDocument('zh', '你建议我怎么做', 'seek_advice');
manager.addDocument('zh', '要不要去', 'seek_advice');
manager.addDocument('zh', '该不该接受', 'seek_advice');
manager.addDocument('zh', '你觉得我应该答应吗', 'seek_advice');

manager.addDocument('zh', '今天天气怎么样', 'ask_fact');
manager.addDocument('zh', 'DeepSeek的股价是多少', 'ask_fact');
manager.addDocument('zh', '今天几号', 'ask_fact');
manager.addDocument('zh', '现在几点', 'ask_fact');
manager.addDocument('zh', '什么是PeppaOS', 'ask_fact');
manager.addDocument('zh', 'DeepSeek是什么', 'ask_fact');
manager.addDocument('zh', '你是什么做的', 'ask_fact');
manager.addDocument('zh', '你的代码是什么语言写的', 'ask_fact');
manager.addDocument('zh', '你多大了', 'ask_fact');
manager.addDocument('zh', '你能做什么', 'ask_fact');
manager.addDocument('zh', '你是哪个公司的', 'ask_fact');
manager.addDocument('zh', 'Peppa是什么意思', 'ask_fact');
manager.addDocument('zh', '什么是数字生命体', 'ask_fact');
manager.addDocument('zh', '你和其他AI有什么不同', 'ask_fact');
manager.addDocument('zh', '你是怎么学习的', 'ask_fact');
manager.addDocument('zh', '你有记忆吗', 'ask_fact');
manager.addDocument('zh', '你能记住我说的话吗', 'ask_fact');
manager.addDocument('zh', '你会忘事吗', 'ask_fact');
manager.addDocument('zh', '你的数据存哪里', 'ask_fact');
manager.addDocument('zh', '你安全吗', 'ask_fact');
manager.addDocument('zh', '谁创造了你', 'ask_fact');
manager.addDocument('zh', '你是什么时候诞生的', 'ask_fact');

manager.addDocument('zh', '今天心情不错', 'chat');
manager.addDocument('zh', '我最近有点累', 'chat');
manager.addDocument('zh', '今天天气真好啊', 'chat');
manager.addDocument('zh', '我心情不太好', 'chat');
manager.addDocument('zh', '今天好开心', 'chat');
manager.addDocument('zh', '最近好忙啊', 'chat');
manager.addDocument('zh', '我在想一个问题', 'chat');
manager.addDocument('zh', '我刚刚做了一个梦', 'chat');
manager.addDocument('zh', '你猜我在想什么', 'chat');
manager.addDocument('zh', '我最近在追一部剧', 'chat');
manager.addDocument('zh', '今天吃了什么好吃的', 'chat');
manager.addDocument('zh', '我有点烦', 'chat');
manager.addDocument('zh', '没事，就是随便聊聊', 'chat');
manager.addDocument('zh', '你最近怎么样', 'chat');
manager.addDocument('zh', '你在干嘛', 'chat');
manager.addDocument('zh', '我想跟你说说话', 'chat');
manager.addDocument('zh', '你睡了吗', 'chat');
manager.addDocument('zh', '你有没有想我', 'chat');
manager.addDocument('zh', '好久没见你说话了', 'chat');
manager.addDocument('zh', '你今天状态怎么样', 'chat');
manager.addDocument('zh', '我挺好的，你呢', 'chat');

async function train() {
  await manager.train();
  const modelPath = path.join(process.cwd(), 'data', 'models', 'nlu-model.nlp');
  await manager.save(modelPath);
  console.log(`模型训练完成并已保存到 ${modelPath}`);
}

train().catch(console.error);
