// Polyfill WebSocket for Node.js (required by MCP SDK's WebSocket transport)
import { WebSocket } from 'ws';
import { logger } from '../lib/logger';
globalThis.WebSocket = WebSocket as any;

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { WebSocketClientTransport } from '@modelcontextprotocol/sdk/client/websocket.js';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { exec } from 'child_process';
import { getDataPath } from '../config/data_path';
import { loadKeys } from '../config/keys';

export interface MCPServerConfig {
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  enabled: boolean;
  source?: 'local' | 'external';      // local = Peppa skill dir, external = third-party
  transport?: 'stdio' | 'http' | 'ws'; // stdio = local process, http = HTTP, ws = WebSocket
  url?: string;                         // URL for remote MCP server (http/ws transport)
  headers?: Record<string, string>;    // custom auth headers for remote connection
  autoGenerated?: boolean;             // true if Peppa generated this skill
  generatedFrom?: string;              // trace: conversation ID or workflow ID
  description?: string;                // human-readable description
  toolCount?: number;                  // cached tool count for UI
  requiresApiKey?: boolean;             // true if startup needs a configured secret
  apiKeyEnv?: string;                   // env/stored key name required by this server
  apiKeyUrl?: string;                   // provider console URL for setup UI
}

export interface MCPToolDef {
  serverName: string;
  name: string;
  description?: string;
  inputSchema: Record<string, any>;
}

export interface SkillPackage {
  name: string;          // directory name / skill id
  description: string;
  toolCount: number;
  autoGenerated: boolean;
  generatedFrom?: string;
  installedAt: string;
  source: 'local' | 'external';
  broken?: boolean;       // dir exists but no index.ts — can be auto-cleaned on reinstall
}

export interface SkillRepairResult {
  success: boolean;
  action?: 'reinstalled' | 'restarted';
  reason?: string;
  directory?: string;
  toolCount?: number;
}

interface ConnectedServer {
  client: Client;
  transport: StdioClientTransport | StreamableHTTPClientTransport | WebSocketClientTransport;
  config: MCPServerConfig;
}

interface MCPConfigFile {
  mcpServers?: Record<string, MCPServerConfig>;
  remoteDevices?: Record<string, string>;
  [key: string]: any;
}

const SKILLS_DIR = getDataPath('skills');

/**
 * 解析 PEPPA_DISABLE_SKILLS（逗号分隔技能名列表，docker-compose.yml 已配置 neteasemusic）。
 * 命中的技能完全跳过：不初始化、不创建子进程、不注册 MCP（Bug 修复：此前该变量零读取，
 * 仅靠技能自身 ERR_MODULE_NOT_FOUND 崩溃"被动屏蔽"）。
 */
function parseDisabledSkills(): Set<string> {
  const raw = (process.env.PEPPA_DISABLE_SKILLS || '').trim();
  if (!raw) return new Set();
  return new Set(raw.split(',').map(s => s.trim().toLowerCase()).filter(Boolean));
}

/**
 * P2-8 供应链防护开关：ALLOW_UNSIGNED_MCP_NPM_PACKAGES（默认 false）。
 * 社区 MCP 通过 npm 包形式加载（installFromNpm → tsx wrapper import），
 * 无法做包签名/完整性校验，属供应链风险。开关关闭时禁止加载任何第三方 npm MCP 包，
 * 抛出风险报错；仅运维显式设 true 才放行（自担供应链信任风险）。
 */
function allowUnsignedNpmMcpPackages(): boolean {
  const v = process.env.ALLOW_UNSIGNED_MCP_NPM_PACKAGES;
  if (v === undefined || v === '') return false;
  return v.toLowerCase() !== 'false' && v !== '0';
}

const DEFAULT_RUNTIME_CONFIG = 'mcp_config.json';
const LEGACY_REPO_CONFIG = path.join(process.cwd(), 'server', 'mcp', 'config.json');
const FACTORY_CONFIG = path.join(process.cwd(), 'server', 'mcp', 'config.example.json');
const DEFAULT_CONFIG_FILE: MCPConfigFile = {
  mcpServers: {
    filesystem: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
      enabled: true,
      source: 'external',
      transport: 'stdio',
      description: 'Filesystem access for the Peppa workspace.',
    },
    sqlite: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-sqlite', 'data/peppa.db'],
      enabled: false,
      source: 'external',
      transport: 'stdio',
      description: 'SQLite access for the local Peppa database.',
    },
    git: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-git', '.'],
      enabled: false,
      source: 'external',
      transport: 'stdio',
      description: 'Git repository inspection tools.',
    },
  },
  remoteDevices: {},
};

function expandPortablePath(value: string): string {
  if (value === '~') return os.homedir();
  if (value.startsWith('~/') || value.startsWith('~\\')) {
    return path.join(os.homedir(), value.slice(2));
  }
  return value.replace(/\$\{PEPPA_SKILLS_DIR\}/g, SKILLS_DIR);
}

function toPortableSkillPath(filePath: string): string {
  const relative = path.relative(SKILLS_DIR, filePath);
  if (relative && !relative.startsWith('..') && !path.isAbsolute(relative)) {
    return `${SKILLS_DIR}/${relative.split(path.sep).join('/')}`;
  }
  return filePath;
}

interface CrashTracker {
  consecutiveCrashes: number;
  lastCrashTime: string;
  lastSuccessfulConnect: string;
  lastError?: string;
  restartTimer: ReturnType<typeof setTimeout> | null;
}

class MCPClientManager {
  private servers: Map<string, ConnectedServer> = new Map();
  private configPath: string;
  private legacyConfigPath: string;
  private factoryConfigPath: string;
  private crashTrackers: Map<string, CrashTracker> = new Map();
  private closingSet: Set<string> = new Set();
  private onServerRecovered?: (name: string, tools: MCPToolDef[]) => void;
  // Bug 修复（MCP 子进程稳定性）：
  //   - connectPromise：connectAll 单飞互斥，杜绝 bootstrap 与 updateMCPConfig 并发双跑
  //     （并发双跑 → 同一 skillId 双份 spawn，后 set 者覆盖 Map，先启动进程成孤儿常驻）；
  //   - connecting：同一 serverName 单实例保护，并发 connectServer/restart 复用同一在途连接。
  private connectPromise: Promise<MCPToolDef[]> | null = null;
  private connecting: Map<string, Promise<MCPToolDef[]>> = new Map();
  private onServerCrashed?: (name: string) => void;
  private ioRef?: any;

  constructor(configPath?: string) {
    this.configPath = configPath || getDataPath(DEFAULT_RUNTIME_CONFIG);
    this.legacyConfigPath = LEGACY_REPO_CONFIG;
    this.factoryConfigPath = FACTORY_CONFIG;
  }

  setSocketIO(io: any): void { this.ioRef = io; }
  setOnServerRecovered(cb: (name: string, tools: MCPToolDef[]) => void): void { this.onServerRecovered = cb; }
  setOnServerCrashed(cb: (name: string) => void): void { this.onServerCrashed = cb; }

  getConfig(): Record<string, MCPServerConfig> {
    return this.readConfigFile().mcpServers || {};
  }

  saveConfig(servers: Record<string, MCPServerConfig>): void {
    const config = this.readConfigFile();
    config.mcpServers = servers;
    this.saveConfigFile(config);
  }

  getRemoteDevices(): Record<string, string> {
    return this.readConfigFile().remoteDevices || {};
  }

  saveRemoteDevices(devices: Record<string, string>): void {
    const config = this.readConfigFile();
    config.remoteDevices = devices;
    this.saveConfigFile(config);
  }

  getConfigPath(): string {
    return this.configPath;
  }

  private readConfigFile(): MCPConfigFile {
    this.ensureRuntimeConfig();
    try {
      let raw = fs.readFileSync(this.configPath, 'utf-8');
      // Replace static relative paths with actual data directory paths
      raw = raw.replace(/"data\/peppa\.db"/g, JSON.stringify(getDataPath('peppa.db')));
      const parsed = JSON.parse(raw);
      if (parsed.mcpServers && typeof parsed.mcpServers === 'object') return parsed;
      return { mcpServers: parsed && typeof parsed === 'object' ? parsed : {} };
    } catch {
      return { mcpServers: {} };
    }
  }

  private saveConfigFile(config: MCPConfigFile): void {
    const dir = path.dirname(this.configPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(this.configPath, `${JSON.stringify(config, null, 2)}\n`);
  }

  private ensureRuntimeConfig(): void {
    if (fs.existsSync(this.configPath)) return;

    const dir = path.dirname(this.configPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const seedPath = fs.existsSync(this.legacyConfigPath)
      ? this.legacyConfigPath
      : this.factoryConfigPath;

    if (seedPath && fs.existsSync(seedPath)) {
      fs.copyFileSync(seedPath, this.configPath);
      return;
    }

    this.saveConfigFile(DEFAULT_CONFIG_FILE);
  }

  // ── Local skill directory management ──

  /** Ensure the skills directory exists */
  private ensureSkillsDir(): void {
    if (!fs.existsSync(SKILLS_DIR)) {
      fs.mkdirSync(SKILLS_DIR, { recursive: true });
    }
  }

  /** List all local skills in ~/peppa_skills/ */
  listLocalSkills(): SkillPackage[] {
    this.ensureSkillsDir();
    const skills: SkillPackage[] = [];
    const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillDir = path.join(SKILLS_DIR, entry.name);
      const pkgPath = path.join(skillDir, 'package.json');
      const indexPath = path.join(skillDir, 'index.ts');

      let pkg: any = {};
      try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}

      const hasIndex = fs.existsSync(indexPath);
      const hasRunCommand = !!pkg.peppa?.runCommand;
      const broken = !hasIndex && !hasRunCommand;

      skills.push({
        name: entry.name,
        description: pkg.description || pkg.peppa?.description || entry.name,
        toolCount: pkg.peppa?.toolCount || 0,
        autoGenerated: pkg.peppa?.autoGenerated || false,
        generatedFrom: pkg.peppa?.generatedFrom,
        installedAt: pkg.peppa?.installedAt || '',
        source: 'local',
        broken,
      });
    }
    return skills;
  }

  /** Install a skill from a source directory into ~/peppa_skills/ */
  installSkill(name: string, sourceDir: string, allowUpgrade = false): string {
    this.ensureSkillsDir();
    const destDir = path.join(SKILLS_DIR, name);

    if (fs.existsSync(destDir)) {
      const hasIndex = fs.existsSync(path.join(destDir, 'index.ts'));
      const pkg = this.readPkg(destDir);
      const hasRunCmd = !!pkg.peppa?.runCommand;
      if (!hasIndex && !hasRunCmd) {
        fs.rmSync(destDir, { recursive: true, force: true });
      } else if (allowUpgrade) {
        // Check if source is newer than installed
        const srcPkg = this.readPkg(sourceDir);
        const srcVersion = srcPkg.version || '0.0.0';
        const installedVersion = pkg.peppa?.installedVersion || '0.0.0';
        if (srcVersion === installedVersion) {
          return destDir; // Already up to date
        }
        logger.info(`[MCP] Upgrading "${name}" ${installedVersion} → ${srcVersion}`);
        fs.rmSync(destDir, { recursive: true, force: true });
      } else {
        throw new Error(`Skill "${name}" already exists. Uninstall it first.`);
      }
    }

    this.copyDirSync(sourceDir, destDir);
    this.installDepsInDir(destDir);
    this.patchInstalledMetadata(destDir);
    // Also stamp the installed version from source
    const srcPkg = this.readPkg(sourceDir);
    this.patchInstalledVersion(destDir, srcPkg.version || '0.0.0');

    const resultingPkg: any = this.readPkg(destDir);
    this.registerLocalSkill(name, destDir, resultingPkg);

    return destDir;
  }

  /** Remove incomplete local skill directories that cannot be started. */
  cleanupBrokenSkills(): string[] {
    const removed: string[] = [];
    for (const skill of this.listLocalSkills()) {
      if (!skill.broken) continue;
      this.uninstallSkill(skill.name);
      removed.push(skill.name);
    }
    return removed;
  }

  /**
   * Try to make an installed skill usable again.
   * Broken npm/GitHub/bundled skills can be reinstalled. Existing local skills
   * get dependencies refreshed and are restarted.
   */
  async repairSkill(name: string): Promise<SkillRepairResult> {
    this.ensureSkillsDir();
    const safeName = path.basename(name);
    if (safeName !== name) {
      return { success: false, reason: 'Invalid skill name' };
    }

    const skillDir = path.join(SKILLS_DIR, name);
    const exists = fs.existsSync(skillDir);
    const config = this.getConfig();
    const serverConfig = config[name];
    if (!exists && !serverConfig) {
      return { success: false, reason: `Skill "${name}" not found` };
    }

    if (!exists && serverConfig?.source === 'local') {
      const bundledPath = path.join(process.cwd(), 'server', 'skills', 'bundled', name);
      if (fs.existsSync(bundledPath)) {
        const directory = this.installSkill(name, bundledPath, true);
        const latest = this.getConfig();
        if (latest[name]) {
          latest[name].enabled = true;
          latest[name].description = (latest[name].description || name).replace(/\s*\(disabled after startup failure:[^)]+\)\s*$/i, '');
          this.saveConfig(latest);
        }
        const tools = await this.restartServer(name);
        return { success: true, action: 'reinstalled', directory, toolCount: tools.length };
      }
    }

    const pkg = exists ? this.readPkg(skillDir) : {};
    const hasIndex = exists && fs.existsSync(path.join(skillDir, 'index.ts'));
    const hasRunCommand = !!pkg.peppa?.runCommand;
    const isBroken = exists && !hasIndex && !hasRunCommand;

    if (isBroken) {
      const npmPackage = pkg.peppa?.npmPackage;
      const repoUrl = pkg.peppa?.repoUrl;
      const bundledPath = path.join(process.cwd(), 'server', 'skills', 'bundled', name);

      if (npmPackage) {
        fs.rmSync(skillDir, { recursive: true, force: true });
        const directory = await this.installFromNpm(npmPackage);
        const latest = this.getConfig();
        if (latest[name]) {
          latest[name].enabled = true;
          this.saveConfig(latest);
        }
        const tools = await this.restartServer(name);
        return { success: true, action: 'reinstalled', directory, toolCount: tools.length };
      }

      if (repoUrl) {
        fs.rmSync(skillDir, { recursive: true, force: true });
        const directory = await this.installFromGitHub(repoUrl);
        const latest = this.getConfig();
        if (latest[name]) {
          latest[name].enabled = true;
          this.saveConfig(latest);
        }
        const tools = await this.restartServer(name);
        return { success: true, action: 'reinstalled', directory, toolCount: tools.length };
      }

      if (fs.existsSync(bundledPath)) {
        const directory = this.installSkill(name, bundledPath, true);
        const latest = this.getConfig();
        if (latest[name]) {
          latest[name].enabled = true;
          this.saveConfig(latest);
        }
        const tools = await this.restartServer(name);
        return { success: true, action: 'reinstalled', directory, toolCount: tools.length };
      }

      return {
        success: false,
        reason: 'Skill package is missing index.ts/runCommand and has no reinstall source. Clean it up, then reinstall or regenerate it.',
      };
    }

    if (exists) {
      this.repairGeneratedSkillSource(skillDir, pkg);
      await this.installDepsSync(skillDir);
      if (!serverConfig) {
        this.registerLocalSkill(name, skillDir, pkg);
      }
    }

    const latest = this.getConfig();
    if (latest[name]) {
      latest[name].enabled = true;
      this.saveConfig(latest);
    }
    const tools = await this.restartServer(name);
    return { success: true, action: 'restarted', directory: exists ? skillDir : undefined, toolCount: tools.length };
  }

  private repairGeneratedSkillSource(skillDir: string, pkg: any): boolean {
    const indexPath = path.join(skillDir, 'index.ts');
    if (!fs.existsSync(indexPath)) return false;
    let source = fs.readFileSync(indexPath, 'utf-8');
    const original = source;
    const isGenerated = Boolean(pkg?.peppa?.autoGenerated) || source.includes('Auto-generated Peppa Skill');
    if (!isGenerated) return false;

    source = this.ensureGeneratedSkillRequire(source);
    source = this.ensureGeneratedSkillResult(source);
    source = this.removeDuplicateGeneratedDestructure(source);
    source = this.removeDuplicateGeneratedParamAliases(source);
    source = this.removeDuplicateGeneratedResultDeclarations(source);
    source = this.fixGeneratedSkillReturns(source);
    source = this.fixGeneratedSkillDescription(source, pkg.description || pkg.peppa?.description || path.basename(skillDir));
    source = source.replace(/z\.array\(z\.any\(\)\)\(\)/g, 'z.array(z.any())');

    if (source !== original) {
      fs.writeFileSync(indexPath, source);
      return true;
    }
    return false;
  }

  private ensureGeneratedSkillRequire(source: string): string {
    if (!/\brequire\(/.test(source) || source.includes('createRequire(import.meta.url)')) return source;
    source = source.replace(
      "import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';",
      "import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';\nimport { createRequire } from 'module';",
    );
    source = source.replace(
      "import fs from 'fs/promises';",
      "import fs from 'fs/promises';\n\nconst require = createRequire(import.meta.url);",
    );
    return source;
  }

  private ensureGeneratedSkillResult(source: string): string {
    const handlerStart = source.indexOf('async function handler(');
    if (handlerStart < 0) return source;
    const handlerEnd = source.indexOf('// ── Schema', handlerStart);
    const handlerBlock = handlerEnd > handlerStart ? source.slice(handlerStart, handlerEnd) : source.slice(handlerStart);
    if (/\b(?:let|var)\s+result(?:\s*=|;)/.test(handlerBlock)) return source;

    return source.replace(
      /(async function handler\([^)]*\): Promise<\{ content: Array<\{ type: 'text'; text: string \}> \}> \{\r?\n(?:\s*const\s*\{[^}]+\}\s*=\s*args;\r?\n|\s*\/\/ No parameters defined\r?\n)?)/,
      `$1  let result = '';\n`,
    );
  }

  private removeDuplicateGeneratedDestructure(source: string): string {
    const seen = new Set<string>();
    return source
      .split(/\r?\n/)
      .filter(line => {
        const trimmed = line.trim();
        if (!/^const\s*\{[^}]+\}\s*=\s*args;$/.test(trimmed)) return true;
        if (seen.has(trimmed)) return false;
        seen.add(trimmed);
        return true;
      })
      .join('\n');
  }

  private removeDuplicateGeneratedParamAliases(source: string): string {
    const destructured = new Set<string>();
    const lines = source.split(/\r?\n/);
    for (const line of lines) {
      const match = line.trim().match(/^const\s*\{\s*([^}]+)\s*\}\s*=\s*args;$/);
      if (!match) continue;
      for (const name of match[1].split(',').map(part => part.trim()).filter(Boolean)) {
        destructured.add(name);
      }
    }
    if (destructured.size === 0) return source;

    return lines
      .filter(line => {
        const match = line.trim().match(/^const\s+([A-Za-z_$][\w$]*)\s*=\s*args\.\1\b.*;$/);
        return !(match && destructured.has(match[1]));
      })
      .join('\n');
  }

  private removeDuplicateGeneratedResultDeclarations(source: string): string {
    let seen = false;
    return source
      .split(/\r?\n/)
      .filter(line => {
        if (!/^\s*let\s+result(?:\s*=.*|;)\s*$/.test(line)) return true;
        if (!seen) {
          seen = true;
          return true;
        }
        return false;
      })
      .join('\n');
  }

  private fixGeneratedSkillReturns(source: string): string {
    return source
      .split(/\r?\n/)
      .map(line => {
        const trimmed = line.trim();
        if (/^return\s+result\s*;?$/.test(trimmed)) return '';
        const valueReturn = trimmed.match(/^return\s+(.+);$/);
        if (valueReturn && !trimmed.includes('content:')) {
          const indent = line.match(/^\s*/)?.[0] || '';
          return `${indent}result = String(${valueReturn[1]});\n${indent}return { content: [{ type: 'text', text: result }] };`;
        }
        return line;
      })
      .join('\n');
  }

  private fixGeneratedSkillDescription(source: string, description: string): string {
    const literal = JSON.stringify(description || 'Generated Peppa skill');
    return source.replace(
      /description:\s*[\s\S]*?\r?\n\s*inputSchema,/,
      `description: ${literal},\n      inputSchema,`,
    );
  }

  /** Check if a bundled source has a newer version than the installed copy */
  isUpgradeAvailable(name: string, sourceDir: string): boolean {
    const destDir = path.join(SKILLS_DIR, name);
    if (!fs.existsSync(destDir)) return false;
    const destPkg = this.readPkg(destDir);
    const srcPkg = this.readPkg(sourceDir);
    const srcVersion = srcPkg.version || '0.0.0';
    const installedVersion = destPkg.peppa?.installedVersion || destPkg.version || '0.0.0';
    return srcVersion !== installedVersion;
  }

  /** Install a skill from an npm package (e.g. "peppa-skill-nanobanana") */
  async installFromNpm(packageName: string): Promise<string> {
    // P2-8 供应链防护：第三方 npm MCP 包无签名/完整性校验，开关（默认 false）关闭时禁止加载
    if (!allowUnsignedNpmMcpPackages()) {
      throw new Error(
        `供应链风险拦截：禁止加载第三方 npm MCP 包 "${packageName}"（无签名/完整性校验）。` +
        '如已显式信任该包来源，请设置环境变量 ALLOW_UNSIGNED_MCP_NPM_PACKAGES=true 后重试。',
      );
    }
    this.ensureSkillsDir();
    const skillName = packageName
      .replace(/^@/, '')
      .replace(/\//g, '-')
      .replace(/[^a-z0-9-]/g, '-');
    const skillDir = path.join(SKILLS_DIR, skillName);

    if (fs.existsSync(skillDir)) {
      const hasIndex = fs.existsSync(path.join(skillDir, 'index.ts'));
      const pkg = this.readPkg(skillDir);
      const hasRunCmd = !!pkg.peppa?.runCommand;
      if (!hasIndex && !hasRunCmd) {
        fs.rmSync(skillDir, { recursive: true, force: true });
      } else {
        throw new Error(`Skill "${skillName}" already exists. Uninstall it first.`);
      }
    }

    // Create a workspace package that depends on the npm MCP skill
    fs.mkdirSync(skillDir, { recursive: true });
    const workspacePkg: any = {
      name: `peppa-skill-${skillName}`,
      version: '1.0.0',
      type: 'module',
      description: `Installed from npm: ${packageName}`,
      dependencies: { [packageName]: '*' },
      peppa: { installedAt: new Date().toISOString(), installedFrom: 'npm', npmPackage: packageName },
    };
    fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(workspacePkg, null, 2));

    // npm install — the dep gets resolved into node_modules/{packageName}
    await this.installDepsSync(skillDir);

    // Read the installed package's package.json for peppa config
    const depPkgPath = path.join(skillDir, 'node_modules', ...packageName.split('/'), 'package.json');
    let depPkg: any = {};
    try { depPkg = JSON.parse(fs.readFileSync(depPkgPath, 'utf-8')); } catch {}

    const peppa = depPkg.peppa || {};

    if (peppa.runCommand) {
      // External MCP with its own run command — use directly
      workspacePkg.peppa.runCommand = peppa.runCommand;
      workspacePkg.peppa.runArgs = peppa.runArgs || [];
      workspacePkg.peppa.toolCount = peppa.toolCount || 0;
      workspacePkg.peppa.requiresApiKey = peppa.requiresApiKey || false;
      workspacePkg.peppa.apiKeyEnv = peppa.apiKeyEnv;
      workspacePkg.peppa.apiKeyUrl = peppa.apiKeyUrl;
      workspacePkg.peppa.description = depPkg.description || peppa.description || packageName;
      fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(workspacePkg, null, 2));
      this.registerLocalSkill(skillName, skillDir, workspacePkg);
    } else if (depPkg.main || depPkg.exports || fs.existsSync(path.join(path.dirname(depPkgPath), 'index.mjs'))) {
      // Standard MCP package: create a tsx wrapper index.ts
      const wrapper = `// Auto-generated wrapper for npm package: ${packageName}
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

async function main() {
  // The npm package exports its own MCP server — import and start
  const mod = await import('${packageName}');
  // If the package exports a server directly, use it; otherwise start via the package's main
  if (mod.server) {
    const transport = new StdioServerTransport();
    await mod.server.connect(transport);
    logger.error('[npm-skill] ${packageName} ready');
  } else if (mod.default?.server) {
    const transport = new StdioServerTransport();
    await mod.default.server.connect(transport);
    logger.error('[npm-skill] ${packageName} ready (default export)');
  } else {
    // Fallback: let the package's entry point handle it (it should be self-booting)
    logger.error('[npm-skill] ${packageName} loaded (self-booting)');
  }
}
main().catch((err) => { logger.error('[npm-skill] Fatal:', err); process.exit(1); });
`;
      fs.writeFileSync(path.join(skillDir, 'index.ts'), wrapper);
      workspacePkg.peppa.toolCount = peppa.toolCount || 1;
      workspacePkg.peppa.description = depPkg.description || peppa.description || packageName;
      workspacePkg.dependencies = workspacePkg.dependencies || {};
      workspacePkg.dependencies['@modelcontextprotocol/sdk'] = '^1.0.0';
      fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(workspacePkg, null, 2));
      await this.installDepsSync(skillDir);
      this.registerLocalSkill(skillName, skillDir, workspacePkg);
    } else {
      throw new Error(`npm package "${packageName}" does not have a peppa MCP config (peppa.runCommand or main entry). Not a valid Peppa skill package.`);
    }

    return skillDir;
  }

  /** Install a skill from a GitHub repository (clone + npm install + register) */
  async installFromGitHub(repoUrl: string): Promise<string> {
    this.ensureSkillsDir();
    const repoName = repoUrl
      .split('/').pop()!
      .replace(/\.git$/, '')
      .replace(/[^a-zA-Z0-9-]/g, '-')
      .toLowerCase();
    const skillDir = path.join(SKILLS_DIR, repoName);

    if (fs.existsSync(skillDir)) {
      const hasIndex = fs.existsSync(path.join(skillDir, 'index.ts'));
      const pkg = this.readPkg(skillDir);
      const hasRunCmd = !!pkg.peppa?.runCommand;
      if (!hasIndex && !hasRunCmd) {
        fs.rmSync(skillDir, { recursive: true, force: true });
      } else {
        throw new Error(`Skill "${repoName}" already exists. Uninstall it first.`);
      }
    }

    logger.info(`[MCP] Cloning ${repoUrl} → ${skillDir}`);
    await new Promise<void>((resolve, reject) => {
      exec(`git clone --depth 1 "${repoUrl}" "${skillDir}"`, { timeout: 60000 }, (err) => {
        err ? reject(new Error(`Git clone failed: ${err.message}`)) : resolve();
      });
    });

    // Run npm install
    await this.installDepsSync(skillDir);

    // Read package.json for peppa config
    let pkg: any = this.readPkg(skillDir);
    const peppa = pkg.peppa || {};

    // Patch install metadata
    if (!pkg.peppa) pkg.peppa = {};
    pkg.peppa.installedAt = new Date().toISOString();
    pkg.peppa.installedFrom = 'github';
    pkg.peppa.repoUrl = repoUrl;
    pkg.peppa.toolCount = peppa.toolCount || 1;
    if (!pkg.description) pkg.description = peppa.description || repoName;
    fs.writeFileSync(path.join(skillDir, 'package.json'), JSON.stringify(pkg, null, 2));

    this.registerLocalSkill(repoName, skillDir, pkg);
    return skillDir;
  }

  /** Run npm install synchronously (awaits completion) */
  private installDepsSync(dir: string): Promise<void> {
    return new Promise((resolve, reject) => {
      exec('npm install --loglevel=error --no-audit --no-fund', {
        timeout: 120000,
        cwd: dir,
      }, (error, _stdout, stderr) => {
        if (error) {
          logger.warn(`[MCP] npm install failed in ${path.basename(dir)}:`, stderr.trim() || error.message);
          reject(new Error(stderr.trim() || error.message));
        } else {
          logger.info(`[MCP] Dependencies installed in ${path.basename(dir)}`);
          resolve();
        }
      });
    });
  }

  private readPkg(dir: string): any {
    const pkgPath = path.join(dir, 'package.json');
    try { return JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch { return {}; }
  }

  private patchInstalledMetadata(dir: string): void {
    const pkgPath = path.join(dir, 'package.json');
    let pkg: any = {};
    try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}
    if (!pkg.peppa) pkg.peppa = {};
    pkg.peppa.installedAt = new Date().toISOString();
    pkg.peppa.autoGenerated = pkg.peppa.autoGenerated || false;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
  }

  /** Stamp the source version onto the installed copy so we can detect upgrades */
  private patchInstalledVersion(dir: string, version: string): void {
    const pkgPath = path.join(dir, 'package.json');
    let pkg: any = {};
    try { pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')); } catch {}
    if (!pkg.peppa) pkg.peppa = {};
    pkg.peppa.installedVersion = version;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
  }

  /** Uninstall a local skill */
  uninstallSkill(name: string): void {
    const skillDir = path.join(SKILLS_DIR, name);
    if (fs.existsSync(skillDir)) {
      fs.rmSync(skillDir, { recursive: true, force: true });
    }

    // Remove from config.json
    const config = this.getConfig();
    if (config[name]) {
      delete config[name];
      this.saveConfig(config);
    }
  }

  /**
   * 直连 node 运行 tsx CLI 入口（node_modules/tsx/dist/cli.mjs）。
   * 替代 `npx tsx <skill>/index.ts`：npx 会拉起 npx → npm exec → sh → node 的 2-4 层进程链，
   * 每技能多占 2-3 个 ~25MB 常驻进程；46 个技能 ≈ 120+ 子进程吃满容器内存（宿主 8G 全局 OOM 根因之一）。
   * node 直接执行 cli.mjs（node 忽略 shebang）进程树只剩 MCP 本体 1 个进程。
   */
  private resolveTsxCli(): string {
    try {
      // require.resolve('tsx') → main（dist/loader.mjs），同目录 cli.mjs 即 CLI 入口
      return path.join(path.dirname(require.resolve('tsx')), 'cli.mjs');
    } catch {
      return path.resolve(process.cwd(), 'node_modules', 'tsx', 'dist', 'cli.mjs');
    }
  }

  /** Register a skill directory as an MCP server entry in config.json */
  private registerLocalSkill(name: string, skillDir: string, pkg: any): void {
    const config = this.getConfig();
    const peppa = pkg.peppa || {};

    // Support external MCP packages with custom run commands
    if (peppa.runCommand) {
      config[name] = {
        command: peppa.runCommand,
        args: peppa.runArgs || [],
        env: peppa.requiresApiKey && peppa.apiKeyEnv
          ? { [peppa.apiKeyEnv]: `\${${peppa.apiKeyEnv}}` }
          : undefined,
        enabled: !peppa.requiresApiKey, // Disable by default if API key needed
        source: 'local',
        transport: 'stdio',
        autoGenerated: peppa.autoGenerated || false,
        generatedFrom: peppa.generatedFrom,
        description: pkg.description || peppa.description || name,
        toolCount: peppa.toolCount,
      };
    } else {
      const indexPath = toPortableSkillPath(path.join(skillDir, 'index.ts'));
      // Build env map from peppa.envKeys (array of key names to pass through from stored keys)
      let env: Record<string, string> | undefined;
      if (peppa.envKeys && Array.isArray(peppa.envKeys)) {
        env = {};
        for (const k of peppa.envKeys) { env[k] = `\${${k}}`; }
      }
      config[name] = {
        // 根因修复：npx tsx → node <cli.mjs> 直跑（每技能 1 进程，替代 2-4 层进程链），详见 resolveTsxCli
        command: 'node',
        args: [this.resolveTsxCli(), indexPath],
        env,
        enabled: true,
        source: 'local',
        autoGenerated: peppa.autoGenerated || false,
        generatedFrom: peppa.generatedFrom,
        description: pkg.description || peppa.description || name,
        toolCount: peppa.toolCount,
      };
    }

    this.saveConfig(config);
  }

  /** Run npm install in a skill directory (fire-and-forget, non-blocking) */
  private installDepsInDir(dir: string): void {
    exec('npm install --loglevel=error --no-audit --no-fund', {
      timeout: 120000,
      cwd: dir,
    }, (error, _stdout, stderr) => {
      if (error) {
        logger.warn(`[MCP] npm install failed in ${dir}:`, stderr.trim() || error.message);
      } else {
        logger.info(`[MCP] Dependencies installed in ${path.basename(dir)}`);
      }
    });
  }

  private copyDirSync(src: string, dest: string): void {
    if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === 'node_modules') continue; // skip, will be installed by user
        this.copyDirSync(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  // ── MCP Server connection management ──

  async connectAll(): Promise<MCPToolDef[]> {
    // 单飞互斥（Bug 修复）：bootstrap 启动路径与 updateMCPConfig（marketplace/skill/mcp 路由）
    // 可能并发触发 connectAll —— 并发双跑会在 servers.set 之前同时通过去重检查、双份 spawn 子进程。
    if (this.connectPromise) return this.connectPromise;
    this.connectPromise = this.connectAllInternal()
      .finally(() => { this.connectPromise = null; });
    return this.connectPromise;
  }

  private async connectAllInternal(): Promise<MCPToolDef[]> {
    // PEPPA_DISABLE_SKILLS（Bug 修复）：命中的技能完全跳过加载（不扫描、不注册、不连接）
    const disabledSkills = parseDisabledSkills();

    // Scan local skills directory and register any unregistered skills
    this.ensureSkillsDir();
    const localEntries = fs.existsSync(SKILLS_DIR)
      ? fs.readdirSync(SKILLS_DIR, { withFileTypes: true })
      : [];
    const config = this.getConfig();

    for (const entry of localEntries) {
      if (!entry.isDirectory()) continue;
      if (disabledSkills.has(entry.name.toLowerCase())) {
        logger.info(`[MCP] ${entry.name}: PEPPA_DISABLE_SKILLS 命中，跳过加载（不初始化、不创建子进程）`);
        continue;
      }
      const skillDir = path.join(SKILLS_DIR, entry.name);
      const indexPath = path.join(skillDir, 'index.ts');
      if (!fs.existsSync(indexPath)) continue;

      if (!config[entry.name]) {
        let pkg: any = {};
        try {
          pkg = JSON.parse(fs.readFileSync(path.join(skillDir, 'package.json'), 'utf-8'));
        } catch {}
        this.registerLocalSkill(entry.name, skillDir, pkg);
      } else if (
        config[entry.name].source === 'local'
        && (config[entry.name].command === 'npx' || config[entry.name].command?.endsWith('/tsx') || config[entry.name].command?.endsWith('.bin/tsx'))
        && (config[entry.name].command === 'npx' ? config[entry.name].args?.[0] === 'tsx' : true)
      ) {
        // 存量配置迁移：旧版 `npx tsx <skill>` / `/app/node_modules/.bin/tsx <skill>` 生成
        // 2-4 层进程链（见 resolveTsxCli 注释），一次性改写为 node <cli.mjs> 直跑，
        // 避免重启后仍按旧命令拉起整条链。tsx bin 形式（command 以 /tsx 结尾）同样覆盖。
        // ⚠️ 必须重新读取文件再保存：`config` 是循环开始前捕获的旧对象，
        // 若前面迭代已注册新技能，用它覆盖会把新技能从配置里抹掉。
        const fresh = this.getConfig();
        const cfg = fresh[entry.name];
        const oldCommand = cfg?.command;
        const isTsxLaunch = cfg
          && cfg.source === 'local'
          && (cfg.command === 'npx' ? cfg.args?.[0] === 'tsx' : cfg.command?.endsWith('/tsx') || cfg.command?.endsWith('.bin/tsx'));
        if (isTsxLaunch) {
          cfg.command = 'node';
          // npx tsx <skill> → 去 tsx 参数；tsx bin 形式 <skill> 直接保留
          cfg.args = [this.resolveTsxCli(), ...cfg.args!.slice(oldCommand === 'npx' ? 1 : 0)];
          this.saveConfig(fresh);
          logger.info(`[MCP] ${entry.name}: 迁移技能启动命令 → node ${this.resolveTsxCli()}`);
        }
      }
    }

    // Reload config after auto-registering local skills
    const finalConfig = this.getConfig();
    const allTools: MCPToolDef[] = [];

    for (const [serverName, serverConfig] of Object.entries(finalConfig)) {
      if (!serverConfig.enabled) continue;
      // PEPPA_DISABLE_SKILLS：配置里已存在的被禁用技能同样跳过（不创建子进程、不注册 MCP）
      if (disabledSkills.has(serverName.toLowerCase())) {
        logger.info(`[MCP] ${serverName}: PEPPA_DISABLE_SKILLS 命中，跳过连接`);
        continue;
      }
      if (this.isMissingRequiredApiKey(serverConfig)) {
        logger.info(`[MCP] ${serverName}: skipped (missing ${serverConfig.apiKeyEnv})`);
        continue;
      }

      try {
        const tools = await this.connectServer(serverName, serverConfig);
        allTools.push(...tools);

        // Update toolCount in config
        if (serverConfig.source === 'local' && serverConfig.toolCount !== tools.length) {
          serverConfig.toolCount = tools.length;
          this.saveConfig(finalConfig);
        }

        logger.info(`[MCP] ${serverName}: ${tools.length} tools discovered (${serverConfig.source || 'external'})`);
      } catch (err: any) {
        logger.warn(`[MCP] Failed to connect to ${serverName}: ${err.message}`);
        if (serverConfig.source === 'local') {
          this.recordStartupFailure(serverName, err);
          logger.warn(`[MCP] Local skill "${serverName}" failed to start. Keeping it enabled and marking health for repair.`);
        }
      }
    }

    return allTools;
  }

  private async connectServer(name: string, config: MCPServerConfig): Promise<MCPToolDef[]> {
    // 单实例保护（Bug 修复）：同一 serverName 只允许一个在途连接。
    // 此前 servers.set 在 await connect 之后，并发调用可同时通过去重检查 → 同一 skillId 双份 spawn，
    // 后 set 者覆盖 Map，先启动的孤儿进程常驻（hk-stock 双实例即此竞态产物）。
    const inFlight = this.connecting.get(name);
    if (inFlight) return inFlight;
    const pending = this.connectServerInternal(name, config)
      .finally(() => { this.connecting.delete(name); });
    this.connecting.set(name, pending);
    return pending;
  }

  private async connectServerInternal(name: string, config: MCPServerConfig): Promise<MCPToolDef[]> {
    // Dedup: if already connected, return cached tools
    const existing = this.servers.get(name);
    if (existing) {
      try {
        const tools = await existing.client.listTools();
        return tools.tools.map((tool: any) => ({
          serverName: name,
          name: `mcp_${name}_${tool.name}`,
          description: tool.description || `${tool.name} (from MCP server: ${name})`,
          inputSchema: tool.inputSchema || { type: 'object', properties: {} },
        }));
      } catch {
        // Stale connection — clean up and reconnect below
        this.servers.delete(name);
      }
    }

    const transportType = config.transport || (config.url ? (config.url.startsWith('wss://') || config.url.startsWith('ws://') ? 'ws' : 'http') : 'stdio');
    let transport: StdioClientTransport | StreamableHTTPClientTransport | WebSocketClientTransport;

    if (transportType === 'ws' && config.url) {
      transport = new WebSocketClientTransport(new URL(config.url));
    } else if (transportType === 'http' && config.url) {
      transport = new StreamableHTTPClientTransport(
        new URL(config.url),
        {
          requestInit: config.headers ? { headers: config.headers } : undefined,
        },
      );
    } else if (config.command) {
      // Expand ${VAR_NAME} placeholders in env values using process.env + stored keys
      const storedKeys: Record<string, string> = {};
      try {
        Object.assign(storedKeys, loadKeys());
      } catch {}
      // 子进程 env = 完整继承主进程环境（LUMI_DATA_DIR/API keys/PEPPA_* 等）+ 技能私有 env。
      // ⚠️ 旧实现仅传技能私有 env：SDK 的 getDefaultEnvironment 只继承 PATH 等白名单变量，
      // 技能侧 getDataPath 等依赖 LUMI_DATA_DIR 的逻辑在 Docker 下会静默解析到错误路径。
      const resolvedEnv: Record<string, string> = { ...process.env };
      if (config.env) {
        for (const [k, v] of Object.entries(config.env)) {
          resolvedEnv[k] = v.replace(/\$\{(\w+)\}/g, (_, name) => process.env[name] || storedKeys[name] || '');
        }
      }
      // stdout 洁净垫片（Bug 修复）：MCP 子进程 stdout 只允许 JSON-RPC 协议流。
      // 技能入口把 console.log/warn 打入 stdout 会破坏 JSON 报文 → 解析报错、工具不可用
      // （meituan-stock-price / stock-price-query / comprehensive-markdown-scraper /
      //   voice-module-status-check 均死于该 bug）。经 NODE_OPTIONS --import 预加载垫片，
      // 在技能代码执行前把 console.log/warn/info 全局重定向到 stderr。
      if (transportType === 'stdio') {
        const shim = path.join(process.cwd(), 'server', 'lib', 'mcp_stdout_shim.mjs');
        if (fs.existsSync(shim)) {
          const prev = resolvedEnv.NODE_OPTIONS || '';
          resolvedEnv.NODE_OPTIONS = [prev, `--import=${shim}`].filter(Boolean).join(' ');
        }
      }
      transport = new StdioClientTransport({
        command: expandPortablePath(config.command),
        args: (config.args || []).map(arg => expandPortablePath(arg)),
        env: resolvedEnv,
      });
    } else {
      throw new Error(`MCP server "${name}": must provide "url" for http/ws transport or "command" for stdio transport`);
    }

    const client = new Client(
      { name: 'peppaOS-mcp-client', version: '2.0' },
      { capabilities: {} },
    );

    try {
      await client.connect(transport);
    } catch (err) {
      // 连接失败/超时：立即关闭 transport 收割子进程（防 esbuild/tsx 僵尸残留），随后原样抛出
      try { await transport.close(); } catch {}
      throw err;
    }

    this.servers.set(name, { client, transport, config });

    // Initialize crash tracker
    if (!this.crashTrackers.has(name)) {
      this.crashTrackers.set(name, {
        consecutiveCrashes: 0,
        lastCrashTime: '',
        lastSuccessfulConnect: new Date().toISOString(),
        restartTimer: null,
      });
    }

    // Install crash detection on transport
    const self = this;
    transport.onclose = () => {
      // If intentionally closing, skip crash detection
      if (self.closingSet.has(name)) {
        self.closingSet.delete(name);
        return;
      }
      // If server still in map, this is an unexpected crash
      if (self.servers.has(name)) {
        logger.info(`[MCP] CRASH DETECTED: "${name}" process exited unexpectedly`);
        self.servers.delete(name);
        const tracker = self.crashTrackers.get(name);
        if (tracker) {
          tracker.lastCrashTime = new Date().toISOString();
        }
        // Bug 修复：崩溃即注销其注册工具（此前仅恢复成功后才注销，崩溃未恢复期间工具残留、计数虚高）
        self.onServerCrashed?.(name);
        self.scheduleRestart(name);
        self.broadcastHealth();
      }
    };

    transport.onerror = (error: Error) => {
      logger.error(`[MCP] Error in "${name}" transport:`, error.message);
    };

    // Reset crash counter on successful connect
    const tracker = self.crashTrackers.get(name)!;
    tracker.consecutiveCrashes = 0;
    tracker.lastSuccessfulConnect = new Date().toISOString();
    if (tracker.restartTimer) {
      clearTimeout(tracker.restartTimer);
      tracker.restartTimer = null;
    }

    const result = await client.listTools();
    return result.tools.map((tool: any) => ({
      serverName: name,
      name: `mcp_${name}_${tool.name}`,
      description: tool.description || `${tool.name} (from MCP server: ${name})`,
      inputSchema: tool.inputSchema || { type: 'object', properties: {} },
    }));
  }

  async callTool(fullName: string, args: Record<string, any>): Promise<string> {
    const match = fullName.match(/^mcp_(.+?)_(.+)$/);
    if (!match) throw new Error(`Invalid MCP tool name: ${fullName}`);

    const [, serverName, toolName] = match;
    const server = this.servers.get(serverName);
    if (!server) throw new Error(`MCP server "${serverName}" not connected`);

    // P2-7: 前置健康检测 — 僵死/重启中/崩溃的 MCP 服务直接快速失败，
    // 跳过底层 30s 超时阻塞等待，避免 LLM 工具循环被卡死
    const health = this.getServerHealth()[serverName];
    if (health && health.status !== 'connected') {
      throw new Error(`MCP server "${serverName}" unhealthy (status=${health.status}, crashes=${health.consecutiveCrashes}) — skipped tool "${toolName}"`);
    }

    const result = await server.client.callTool({ name: toolName, arguments: args });

    const contents = (result as any).content || [];
    return contents
      .filter((c: any) => c.type === 'text')
      .map((c: any) => c.text)
      .join('\n');
  }

  async disconnectAll(): Promise<void> {
    // Cancel all pending restart timers
    for (const [n, tracker] of this.crashTrackers) {
      if (tracker.restartTimer) {
        clearTimeout(tracker.restartTimer);
        tracker.restartTimer = null;
      }
    }
    for (const [name, server] of this.servers) {
      this.closingSet.add(name);
      try {
        await server.transport.close();
      } catch {}
    }
    this.servers.clear();
    this.closingSet.clear();
  }

  async restartServer(name: string): Promise<MCPToolDef[]> {
    // PEPPA_DISABLE_SKILLS：被禁用技能即使被手动重启也拒绝拉起子进程
    if (parseDisabledSkills().has(name.toLowerCase())) {
      logger.warn(`[MCP] ${name}: PEPPA_DISABLE_SKILLS 命中，拒绝重启`);
      return [];
    }
    const server = this.servers.get(name);
    if (server) {
      this.closingSet.add(name);
      try { await server.transport.close(); } catch {}
      this.servers.delete(name);
      this.closingSet.delete(name);
    }

    const config = this.getConfig();
    const serverConfig = config[name];
    if (!serverConfig || !serverConfig.enabled) return [];

    return this.connectServer(name, serverConfig);
  }

  /** Disconnect a server without restarting it (used when disabling) */
  async disconnectServer(name: string): Promise<void> {
    const server = this.servers.get(name);
    if (server) {
      this.closingSet.add(name);
      try { await server.transport.close(); } catch {}
      this.servers.delete(name);
      this.closingSet.delete(name);
    }
  }

  private scheduleRestart(name: string): void {
    const tracker = this.crashTrackers.get(name);
    if (!tracker) return;

    if (tracker.restartTimer) {
      clearTimeout(tracker.restartTimer);
    }

    // Max 5 consecutive crashes before giving up
    if (tracker.consecutiveCrashes >= 5) {
      logger.error(`[MCP] "${name}" crashed ${tracker.consecutiveCrashes} times — giving up. Manual intervention required.`);
      return;
    }

    const delay = Math.min(1000 * Math.pow(2, tracker.consecutiveCrashes), 60000);
    tracker.consecutiveCrashes++;

    logger.info(`[MCP] Scheduling restart for "${name}" in ${delay}ms (crash #${tracker.consecutiveCrashes})`);

    tracker.restartTimer = setTimeout(async () => {
      tracker.restartTimer = null;
      try {
        const config = this.getConfig();
        const serverConfig = config[name];
        if (!serverConfig || !serverConfig.enabled) {
          logger.info(`[MCP] Server "${name}" is now disabled, skipping restart`);
          return;
        }

        const tools = await this.connectServer(name, serverConfig);
        logger.info(`[MCP] "${name}" restarted successfully with ${tools.length} tools`);

        tracker.consecutiveCrashes = 0;
        tracker.lastSuccessfulConnect = new Date().toISOString();

        this.onServerRecovered?.(name, tools);
      } catch (err: any) {
        tracker.lastError = String(err?.message || err);
        logger.error(`[MCP] Restart attempt for "${name}" failed: ${err.message}`);
      }
      this.broadcastHealth();
    }, delay);
  }

  private isMissingRequiredApiKey(config: MCPServerConfig): boolean {
    if (!config.requiresApiKey || !config.apiKeyEnv) return false;
    const fromEnv = process.env[config.apiKeyEnv]?.trim();
    if (fromEnv) return false;
    try {
      return !loadKeys()[config.apiKeyEnv]?.trim();
    } catch {
      return true;
    }
  }

  private recordStartupFailure(name: string, err: any): void {
    let tracker = this.crashTrackers.get(name);
    if (!tracker) {
      tracker = {
        consecutiveCrashes: 0,
        lastCrashTime: '',
        lastSuccessfulConnect: '',
        restartTimer: null,
      };
      this.crashTrackers.set(name, tracker);
    }
    tracker.lastCrashTime = new Date().toISOString();
    tracker.lastError = String(err?.message || err);
    this.scheduleRestart(name);
    this.broadcastHealth();
  }

  getServerHealth(): Record<string, { status: string; consecutiveCrashes: number; lastCrashTime?: string; lastSuccessfulConnect?: string; lastError?: string }> {
    const config = this.getConfig();
    const health: Record<string, any> = {};
    for (const [name] of Object.entries(config)) {
      const tracker = this.crashTrackers.get(name);
      const isRestarting = !!tracker?.restartTimer;
      health[name] = {
        status: isRestarting ? 'restarting'
          : this.servers.has(name) ? 'connected'
          : (tracker?.consecutiveCrashes ?? 0) >= 5 ? 'failed'
          : (tracker?.consecutiveCrashes ?? 0) > 0 ? 'crashed'
          : 'disconnected',
        consecutiveCrashes: tracker?.consecutiveCrashes || 0,
        lastCrashTime: tracker?.lastCrashTime || undefined,
        lastSuccessfulConnect: tracker?.lastSuccessfulConnect || undefined,
        lastError: tracker?.lastError || undefined,
      };
    }
    return health;
  }

  private broadcastHealth(): void {
    if (this.ioRef) {
      this.ioRef.emit('mcp:health_update', { servers: this.getServerHealth() });
    }
  }

  getConnectedServers(): string[] {
    return Array.from(this.servers.keys());
  }
}

export const mcpManager = new MCPClientManager();
export { SKILLS_DIR };
